version: '3'
services:
  database:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    tty: true
    build:
          context: ./database
          args:
              - MYSQL_DATABASE=${MYSQL_DATABASE}
              - MYSQL_USER=${MYSQL_USER}
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    command: --innodb-use-native-aio=0
    volumes:
          - "./database/db/:/var/lib/mysql"
    networks:
      - new
  back:
    container_name: back
    depends_on:
      - database
    stdin_open: true
    links:
      - database
    build: 
          context: ./back
          args:
              - MYSQL_DATABASE=${MYSQL_DATABASE}
              - MYSQL_USER=${MYSQL_USER} 
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
            - 3000:3000
    networks:
      - new
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    depends_on:
      - back
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./data/certbot/conf:/etc/letsencrypt"
      - "./data/certbot/www:/var/www/certbot"
    # command: certonly --webroot -w /var/www/certbot --force-renewal --email {CERTBOT_EMAILS} -d {DOMAINS} --agree-tos
    networks:
      - new
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    env_file:
      - ./.env
    depends_on:
      - nginx
    build:
          context: ./certbot
          args:
              - DOMAINS=${DOMAINS}
              - CERTBOT_TEST_CERT=${CERTBOT_TEST_CERT}
              - CERTBOT_EMAILS=${CERTBOT_EMAILS}
              - CERTBOT_RSA_KEY_SIZE=${CERTBOT_RSA_KEY_SIZE}
    restart: always
    build: 
          context: ./certbot
          args:
              - DOMAINS=${DOMAINS}

    volumes:
      - "./data/certbot/conf:/etc/letsencrypt"
      - "./data/certbot/www:/var/www/certbot"
    networks:
    - new
networks:
  new:

